# set base mirror
FROM samge/ai-env:cuda11.8.0-cudnn8-devel-ubuntu22.04-python3.10.13-torch2.2.0 as base

ARG PROXY
ENV http_proxy=${PROXY} https_proxy=${PROXY}

FROM base as requirements

RUN apt update -y && apt -y install -qq aria2

RUN pip install -q einops transformers controlnet-aux==0.0.7 sentencepiece imageio imageio-ffmpeg

# use known version number
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

# 重置代理配置
ENV http_proxy= https_proxy=
